# Generated by Django 5.1.5 on 2025-02-08 04:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MovieModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("release_date", models.DateField(default=django.utils.timezone.now)),
                ("movie_name", models.CharField(max_length=30)),
                ("hero_name", models.CharField(max_length=30)),
                ("heroine_name", models.CharField(max_length=30)),
                ("movie_ratings", models.IntegerField()),
                ("director_name", models.CharField(max_length=44)),
            ],
        ),
    ]
