# Generated by Django 5.1.5 on 2025-02-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbvApp", "0002_company_employee"),
    ]

    operations = [
        migrations.CreateModel(
            name="Beer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("taste", models.CharField(max_length=128)),
                ("color", models.CharField(max_length=128)),
                ("price", models.FloatField()),
            ],
        ),
    ]
