# Generated by Django 5.1.5 on 2025-02-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testapp",
            name="gender",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="testapp",
            name="name",
            field=models.CharField(default="as", max_length=50),
        ),
        migrations.AlterField(
            model_name="testapp",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
